import {load,patch} from '/Users/chloeongsiyi/Trenchcoons/.critic/probe.mjs';
const R='/Users/chloeongsiyi/Trenchcoons/';
const cliff=load(R+'shots/forge/forge-cliff.png');
console.log('cliff-block LIT top plane   ', JSON.stringify(patch(cliff,960,300,60,40)));
console.log('cliff-block LIT lower face  ', JSON.stringify(patch(cliff,940,500,80,60)));
console.log('cliff-block SHADOW right    ', JSON.stringify(patch(cliff,1190,420,60,80)));
console.log('cliff-block SHADOW dark face', JSON.stringify(patch(cliff,1160,480,40,60)));
const rock=load(R+'shots/forge/forge-rock.png');
console.log('rock-med LIT top            ', JSON.stringify(patch(rock,1000,480,120,30)));
console.log('rock-med SHADOW side        ', JSON.stringify(patch(rock,1090,560,90,30)));
const trees=load(R+'shots/forge/forge-trees.png');
console.log('conifer LIT tier            ', JSON.stringify(patch(trees,790,540,50,40)));
console.log('conifer SHADOW tier         ', JSON.stringify(patch(trees,950,500,40,40)));
const veg=load(R+'shots/forge/forge-veg.png');
console.log('shrub-broadleaf body        ', JSON.stringify(patch(veg,1150,420,120,80)));
console.log('bush-round body             ', JSON.stringify(patch(veg,740,440,60,50)));
console.log('grass ground control (veg)  ', JSON.stringify(patch(veg,300,700,200,100)));
const props=load(R+'shots/forge/forge-props.png');
console.log('deadwood log                ', JSON.stringify(patch(props,460,450,50,50)));
console.log('stump                       ', JSON.stringify(patch(props,860,440,40,50)));
