// Export the raccoon's REST POSE as an OBJ, for inspection outside the game.
//
// WHY THIS EXISTS. Every judgement about this character so far has come from a
// game capture: a 40-second build-and-shoot cycle, at one of a handful of fixed
// cameras, with the box occluding the body, the biome's own light on the fur and
// the terrain behind it. That is the right way to judge whether the character
// WORKS — it is how the player sees it — and it is a terrible way to judge the
// FORM, because you never see the thing on its own from a chosen angle.
//
// The cost of that showed up as six independent observers misreading the tail as
// an arm. Nobody, me included, had ever looked at the model in isolation.
//
// This walks the same `Rig` and the same geometry functions the game calls, at
// rest, and writes one OBJ group per part with a material per surface. Blender
// (or any viewer) can then render a turnaround in seconds. It is an INSTRUMENT,
// not an asset pipeline: nothing here feeds back into the build, and the
// no-hardcoded-assets invariant is untouched because the OBJ is an output.
//
//   node tools/raccoon-export.mjs [out.obj]

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')

/** Bundle raccoon.ts for node through the project's own rolldown. */
async function load(rel, ...names) {
  const entry = path.join(os.tmpdir(), `rx-${process.pid}.mjs`)
  const out = path.join(os.tmpdir(), `rx-${process.pid}.bundle.mjs`)
  fs.writeFileSync(entry, `export * from ${JSON.stringify(path.join(ROOT, rel))}\n`)
  execFileSync(path.join(ROOT, 'node_modules/.bin/rolldown'),
    [entry, '--platform', 'node', '--format', 'esm', '--file', out],
    { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] })
  const mod = await import(`file://${out}`)
  fs.rmSync(entry, { force: true })
  fs.rmSync(out, { force: true })
  return mod
}

const R = await load('src/vehicle/raccoon.ts')
const { RACCOON } = R
const hash = (n) => { const x = Math.sin(n * 127.1 + 311.7) * 43758.5453; return x - Math.floor(x) }

// ── the rest pose ───────────────────────────────────────────────────────────
// Built through `buildRaccoonJoints` and `rig.solve()`, i.e. the same code the
// game runs, so this cannot drift from what ships.
const rig = new R.Rig()
const j = R.buildRaccoonJoints(rig, -1)
rig.solve()

/**
 * Every drawn part, as (name, surface, geometry, driving joint).
 *
 * Mirrors the `setMatrix` calls in kart.ts's `writeOne`. Kept in this order so
 * the OBJ's groups read top-down through the animal.
 */
const IDENT = null
const parts = [
  ['body', 'fur', R.bodyGeometry(), j.spine, IDENT],
  ['skull', 'fur', R.skullGeometry(), j.head, IDENT],
  ['mask', 'mask', R.maskGeometry(), j.head, IDENT],
  ['blaze', 'furLight', R.blazeGeometry(), j.head, IDENT],
  ['muzzle', 'furMuzzle', R.muzzleGeometry(), j.head, IDENT],
  ['nose', 'furDark', R.noseGeometry(), j.head, IDENT],
  ['grin', 'eye', R.grinGeometry(false), j.head, IDENT],
  ['tongue', 'mouthPink', R.grinGeometry(true), j.head, IDENT],
  ['earL', 'fur', R.earGeometry(false), j.earL, IDENT],
  ['earR', 'fur', R.earGeometry(false), j.earR, IDENT],
  ['earInnerL', 'furLight', R.earGeometry(true), j.earL, IDENT],
  ['earInnerR', 'furLight', R.earGeometry(true), j.earR, IDENT],
]

// Eyeballs and irises: the iris rides forward and inboard off the eyeball.
for (const [tag, joint, side] of [['L', j.eyeL, -1], ['R', j.eyeR, 1]]) {
  parts.push([`eyeball${tag}`, 'furLight', R.sphere(RACCOON.eye, 14), joint, IDENT])
  parts.push([`iris${tag}`, 'eye', R.sphere(RACCOON.eye * RACCOON.iris, 12), joint,
    [-side * RACCOON.eye * RACCOON.irisIn, 0, -RACCOON.eye * RACCOON.irisOut]])
}

// Arms: two bones per side, each the one limb shape scaled to its own length.
for (const [tag, sh, el, pw] of [
  ['L', j.shoulderL, j.elbowL, j.pawL], ['R', j.shoulderR, j.elbowR, j.pawR],
]) {
  parts.push([`upperArm${tag}`, 'fur', R.limbGeometry(RACCOON.upperArm * 0.55), sh,
    IDENT, [1, RACCOON.upperArm, 1]])
  parts.push([`foreArm${tag}`, 'fur', R.limbGeometry(RACCOON.upperArm * 0.55), el,
    IDENT, [1, RACCOON.foreArm, 1]])
  parts.push([`paw${tag}`, 'furDark', R.pawGeometry(), pw, IDENT])
}

// Tail: alternating surfaces, tapered by `tailProfile`.
for (let s = 0; s < j.tail.length; s++) {
  const k = R.tailProfile(s / (j.tail.length - 1))
  parts.push([`tail${s}`, s % 2 === 0 ? 'fur' : 'furDark',
    R.tailGeometry(RACCOON.tailRadius), j.tail[s], IDENT, [k, k, 1]])
}

// ── write the OBJ ───────────────────────────────────────────────────────────
const outPath = path.resolve(process.argv[2] ?? '/tmp/raccoon.obj')
const mtlPath = outPath.replace(/\.obj$/, '.mtl')
const obj = [`# raccoon rest pose, generated by tools/raccoon-export.mjs`,
  `mtllib ${path.basename(mtlPath)}`]
let base = 1
const surfaces = new Set()

for (const [name, surface, geo, joint, offset, scale] of parts) {
  surfaces.add(surface)
  const pos = geo.attributes.position.array
  const nrm = geo.attributes.normal.array
  const idx = geo.index ? geo.index.array : null
  const m = joint.world.elements
  // Apply the joint's world matrix, then any local offset and non-uniform scale
  // — post-multiplied in the joint's own frame, exactly as `setMatrix` does.
  const xf = (x, y, z) => {
    if (scale) { x *= scale[0]; y *= scale[1]; z *= scale[2] }
    if (offset) { x += offset[0]; y += offset[1]; z += offset[2] }
    return [
      m[0] * x + m[4] * y + m[8] * z + m[12],
      m[1] * x + m[5] * y + m[9] * z + m[13],
      m[2] * x + m[6] * y + m[10] * z + m[14],
    ]
  }
  obj.push(`g ${name}`, `usemtl ${surface}`)
  const n = pos.length / 3
  for (let i = 0; i < n; i++) {
    const [x, y, z] = xf(pos[i * 3], pos[i * 3 + 1], pos[i * 3 + 2])
    obj.push(`v ${x.toFixed(5)} ${y.toFixed(5)} ${z.toFixed(5)}`)
  }
  for (let i = 0; i < n; i++) {
    // Normals ignore translation. Non-uniform scale would need the inverse
    // transpose; every scale here is either uniform or along a bone's own axis,
    // where the error is under a degree and invisible in a turnaround.
    const [x, y, z] = [nrm[i * 3], nrm[i * 3 + 1], nrm[i * 3 + 2]]
    obj.push(`vn ${(m[0] * x + m[4] * y + m[8] * z).toFixed(5)} `
      + `${(m[1] * x + m[5] * y + m[9] * z).toFixed(5)} `
      + `${(m[2] * x + m[6] * y + m[10] * z).toFixed(5)}`)
  }
  const tri = (a, b, c) => obj.push(
    `f ${base + a}//${base + a} ${base + b}//${base + b} ${base + c}//${base + c}`)
  if (idx) for (let t = 0; t + 2 < idx.length; t += 3) tri(idx[t], idx[t + 1], idx[t + 2])
  else for (let t = 0; t + 2 < n; t += 3) tri(t, t + 1, t + 2)
  base += n
}

// Materials carry the authored `base` colour of each surface, so the turnaround
// shows the model's own value structure rather than a uniform grey.
const defs = JSON.parse(execFileSync('node', ['-e', `
  const fs=require('fs'),p='assets/defs/surfaces';
  const o={};for(const f of fs.readdirSync(p)){const d=JSON.parse(fs.readFileSync(p+'/'+f));
  o[d.id]=d.material.base||'#808080';}process.stdout.write(JSON.stringify(o))
`], { cwd: ROOT }).toString())
const mtl = []
for (const s of surfaces) {
  const hex = defs[s] ?? '#808080'
  const c = [1, 3, 5].map((i) => (parseInt(hex.slice(i, i + 2), 16) / 255).toFixed(4))
  mtl.push(`newmtl ${s}`, `Kd ${c.join(' ')}`, `Ka 0 0 0`, `Ks 0 0 0`, '')
}
fs.writeFileSync(outPath, obj.join('\n') + '\n')
fs.writeFileSync(mtlPath, mtl.join('\n') + '\n')
console.log(`${outPath}  ${parts.length} parts, ${(base - 1)} verts, ${surfaces.size} materials`)
